name: classimed
description: Aplicativo para classificação de incidentes médicos - ClassiMed
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  shared_preferences: ^2.2.2
  flutter_email_sender: ^6.0.3
  http: ^1.2.2
  pdf: ^3.10.7
  printing: ^5.13.0 
  flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo-robo-nome.png
    - .env